### PR TITLE
trying pull again after removing uppercase BIDSMRI2NIDM and CSV2NIDM

### PR DESCRIPTION
**Pull request by dbkeator**

### CODE REVIEW

**Comment by dbkeator** [comment]
@djarecka Can you help me diagnose this problem?  I've tried many times now to change the case of BIDSMRI2NIDM.py and CSV2NIDM.py in my [fork](https://github.com/dbkeator/PyNIDM).  It appears to me that I have.  I've cloned it and installed it with pip in a new conda environment and there are no issues.  Travis seems to be having the issue but I can't seem to figure out why.  Thought you might have an idea or could at least test cloning my repo and installing pynidm into a new conda environment and see if you get any errors....Thx

**Comment by djarecka** [comment]
@dbkeator - i've installed PyNIDM and also have errors. I'm having issues that `urllib.request.urlretrieve` can't find urls, and I actually also can't find them...

Is it possible that you already have some files in your directory (e.g. `cmu_a.nidm.ttl`), so when you run the tests, python doesn't try to download new files, so it works for you? See example here: https://github.com/dbkeator/PyNIDM/blob/master/nidm/experiment/tools/tests/test_rest.py#L37
(Perhaps, you should remove the if statement from the tests and always download the files)

**Comment by dbkeator** [comment]
@djarecka Lol, that's a new problem caused by me reorganizing the simple2_NIDM_examples repo yesterday to merge the wBrainVols branch and master.  That's a test Al Crowley inserted.  I think it's unrelated but I'll do an update and push to my repo and we'll see if that results in any difference for TravisCI

**Comment by dbkeator** [comment]
@djarecka Ok weird, just changing the test case URL fixed the other issue I was seeing with TravisCI.  I wonder why it didn't tell me that yesterday and kept complaining about bin/BIDSMRI2NIDM which didn't exist.  Ugh, spent so much time trying to figure that out...Thanks for the help!  I knew you'd figure it out! :)

**Comment by dbkeator** [comment]
@albertcrowley You'll want to update your copy of PyNIDM.  Besides other unrelated changes, I merged the simple2_NIDM_examples wBrainVols branch with master and then updated your rest API test cases....

**Pull request merged**
