### PR TITLE
a simple instruction to install with conda on osx

### PR DESCRIPTION
**Pull request by djarecka**

### CODE REVIEW

**Comment by khelm** [comment]
Is this specific to OSX?

**Comment by djarecka** [comment]
@khelm didn't test anywhere else. I guess linux doesn't complain about `dot

**Comment by khelm** [comment]
Ok, thanks.

**Comment by satra** [comment]
@djarecka  - needs a bit of conflict resolution and update. pydot is now part of requirements, so it should install without update.

**Pull request closed without merging**
