### PR TITLE
Created new reStructuredText README + sphinx documentation

### PR DESCRIPTION
**Pull request by dbkeator**
Started working on documentation.  Now using README.rst for root of main repo and set up initial "Read the docs" documentation...

[https://pynidm.readthedocs.io/en/latest/?](url)

### CODE REVIEW

**Comment by satra** [comment]
@dbkeator - can we use markdown?

http://www.sphinx-doc.org/en/master/usage/markdown.html

**Comment by satra** [comment]
but i'm not hundred percent wedded to using markdown - just that it's simpler than some of the constructions of RST, and in some cases being able to embed raw html can be a plus.

**Comment by dbkeator** [comment]
I'm really liking RST right now.  We've been using markdown for awhile....

**Comment by dbkeator** [comment]
It shouldn't be that hard to switch, we don't have all that much documentation...let's go with RST for a bit and if we don't like it I'll convert back to markdown.

**Pull request merged**
