### PR TITLE
hacked hash of data dictionary key to accommodate bug in rdflib where … …

### PR DESCRIPTION
**Pull request by dbkeator**

### CODE REVIEW

**Comment by satra** [comment]
> hacked hash of data dictionary key to accomodate bug in rdflib where localpart of qnames that begin with numbers get added to the namespace and a new random prefix is generated. Hack involves simply replacing the first digit of hash with random hexidecimal letter

is this still true with `neurdflib` (cc: @tgbugs)?

**Comment by dbkeator** [comment]
@satra Don't know.  Haven't moved over to neurdflib yet.  There's always something more pressing and will require some time to be spent testing the API and various tools as the automated test cases aren't complete.  Currently I'm just trying to get the CoRR BIDS data converted to NIDM and brain volumes added to it so I can give Kennedy.Dave a better N for things like "number of males and females in datasets on ReproLake", "number of participants with T1w", etc.

**Comment by tgbugs** [comment]
The qname issue as described should definitely be fixed by switching to `neurdflib`.

**Comment by satra** [comment]
@dbkeator - it's already in pynidm:

https://github.com/incf-nidash/PyNIDM/blob/master/nidm/version.py#L61

all you need to do in your python environment is do: `pip install --upgrade neurdflib`

**Pull request merged**
