### PR TITLE
map_variables_to_terms adds new term definitions directly to Interlex

### PR DESCRIPTION
**Pull request by dbkeator**
see: [https://github.com/dbkeator/PyNIDM/blob/master/nidm/experiment/Utils.py#L332]

see: [https://github.com/dbkeator/PyNIDM/blob/master/nidm/experiment/Utils.py#L348]

### CODE REVIEW

**Comment by dbkeator** [comment]
@djarecka @cmaumet  

Hi, I've added a few new functions to directly store terms in Interlex which required me to add a dependency (https://github.com/tgbugs/ontquery/tree/master).  This results in the travis build failing.  I tried changing setup.py to require the dependency: [https://github.com/incf-nidash/PyNIDM/pull/120/commits/da303ddd5f7a18216fdaa7096d9e9fa22b6bd77a#diff-2eeaed663bd0d25b7e608891384b7298R23](url) but that didn't seem to work.  Do you know how I can fix this?  Thanks!

**Comment by djarecka** [comment]
@dbkeator - sorry that takes so long, will do it right after our meeting

**Comment by djarecka** [comment]
@dbkeator  - I fixed the issue with the ontquery - I added the lib to version.py (instead of setup) and had to  remove py35 from Travis, since the library uses syntax that is not supported by py < 3.6

I've created a PR to your fork, but unfortunately there are many other older commits in the PR - for some reason the commits are in the main incf-nidash:master repository, but not in your repository (you can compare for example the experiment/tools directory and see that you have different files). I was trying to study the history, but gave up. At some point it would be good if you add the commits to your master, either by accepting my PR or separately. 

I'm guessing that the main problem is that you're using master branch to work on new code and always push your changes to incf-nidash:master, but sometimes forget pull/fetch from the main repo, so you're ignoring changes that were approved. At the end your master is lacking some commits.

**Comment by dbkeator** [comment]
@djarecka Thanks!

**Pull request merged**
